services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  backend:
    build:
      context: ./api.fluvimar.controle-de-atestados-ddd
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  postgres_data:
